# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from curses import ERR
#from pickle import TRUE
#from tkinter import Button


from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import sys
import os
import subprocess
from os import *



class Ui_SecondWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 900)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 20, 581, 929))
        self.widget.setStyleSheet(u"QPushButton#pushButton{\n"
"	background-color: qlinegradient(spread:pad, x1:0, y1:0,505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"	background-color: qlinegradient(spread:pad, x1:0, y1:0,505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"	padding-left:5px;\n"
"	padding:top;\n"
"	background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_6, #pushButton_7{\n"
"	background-color: rgba(0, 0, 0, 0);\n"
"	color:rgba(85, 98, 112, 255);\n"
"}\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_6:hover, #pushButton_7:hover{\n"
"	color: rgba(155, 168, 182, 200);\n"
"}\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_6:pressed, #pushButton_7:pressed{\n"
""
                        "	padding-left:5px;\n"
"	padding:top;\n"
"	background-color:rgba(115, 128, 142, 255);\n"
"}")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 40, 500, 780))
        self.label.setStyleSheet(u"border-image: url(7f631e577ed5e5ffbbce726f8ec03489.jpg);\n"
"border-radius:20px;\n"
"")
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 20, 530, 820))
        self.label_2.setStyleSheet(u"background-color: qlinegradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius:20px;\n"
"")
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 70, 440, 720))
        self.label_3.setStyleSheet(u"background: rgba(0,0,0,100);\n"
"border-radius : 15px")
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(190, 130, 211, 71))
        font = QFont()
        font.setFamily(u"Corbel")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        self.label_4.setTextFormat(Qt.PlainText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.pushButton_3 = QPushButton(self.widget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(470, 90, 31, 31))
        font1 = QFont()
        font1.setFamily(u"Corbel")
        font1.setPointSize(21)
        font1.setBold(True)
        font1.setWeight(75)
        self.pushButton_3.setFont(font1)
        self.pushButton_3.setStyleSheet(u"color:rgba(255,255,255,210);")
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(190, 280, 41, 41))
        font2 = QFont()
        font2.setFamily(u"Corbel")
        font2.setPointSize(16)
        font2.setBold(True)
        font2.setWeight(75)
        self.label_5.setFont(font2)
        self.label_5.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(190, 320, 41, 41))
        self.label_6.setFont(font2)
        self.label_6.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(190, 360, 41, 41))
        self.label_7.setFont(font2)
        self.label_7.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(190, 400, 41, 41))
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(190, 440, 41, 41))
        self.label_9.setFont(font2)
        self.label_9.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(190, 480, 41, 41))
        self.label_10.setFont(font2)
        self.label_10.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(190, 520, 41, 41))
        self.label_11.setFont(font2)
        self.label_11.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(370, 280, 41, 41))
        self.label_12.setFont(font2)
        self.label_12.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(370, 320, 41, 41))
        self.label_13.setFont(font2)
        self.label_13.setStyleSheet(u"color:rgba(255, 255, 255, 190);")
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(370, 360, 41, 41))
        self.label_14.setFont(font2)
        self.label_14.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(self.widget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(370, 400, 41, 41))
        self.label_15.setFont(font2)
        self.label_15.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.widget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(370, 440, 41, 41))
        self.label_16.setFont(font2)
        self.label_16.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.widget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(370, 480, 41, 41))
        self.label_17.setFont(font2)
        self.label_17.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.widget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(370, 520, 41, 41))
        self.label_18.setFont(font2)
        self.label_18.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.label_18.setAlignment(Qt.AlignCenter)
        #self.label_19 = QLabel(self.widget)
        #self.label_19.setObjectName(u"label_19")
        #self.label_19.setGeometry(QRect(160, 259, 271, 321))
        #self.label_19.setStyleSheet(u"background: rgba(0,0,0,100);\n"
#"border-radius : 15px")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"BENGALURU", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"AQI", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"PM", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"CO", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"O3", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"SO2", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"NO2", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"108", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"68", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"38", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"19", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"01", None))
        #self.label_19.setText("")
        self.pushButton_3.clicked.connect(QCoreApplication.instance().quit)
 
     
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())