# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'App_InterfacerMuIAQ.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginInterface.ui'
#
# Created by: PyQt6 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from curses import ERR
#from pickle import TRUE
#from tkinter import Button



from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6 import *
import sys
import os
import subprocess
from os import *



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 900)
        self.centralwidget = QWidget(MainWindow)
        #MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        #MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        MainWindow.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 20, 387, 929))
        self.widget.setStyleSheet(u"QPushButton#pushButton{\n"
"	background-color: qlinegradient(spread:pad, x1:0, y1:0,505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"	background-color: qlinegradient(spread:pad, x1:0, y1:0,505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"	padding-left:5px;\n"
"	padding:top;\n"
"	background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_6, #pushButton_7{\n"
"	background-color: rgba(0, 0, 0, 0);\n"
"	color:rgba(85, 98, 112, 255);\n"
"}\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_6:hover, #pushButton_7:hover{\n"
"	color: rgba(155, 168, 182, 200);\n"
"}\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_6:pressed, #pushButton_7:pressed{\n"
""
                        "	padding-left:5px;\n"
"	padding:top;\n"
"	background-color:rgba(115, 128, 142, 255);\n"
"}")
        self.picture_label = QLabel(self.widget)
        self.picture_label.setObjectName(u"picture_label")
        self.picture_label.setGeometry(QRect(30, 40, 334, 780))
        self.picture_label.setStyleSheet(u"border-image: url(7f631e577ed5e5ffbbce726f8ec03489.jpg);\n"
"border-radius:20px;\n"
"")
        self.translucent_window_label = QLabel(self.widget)
        self.translucent_window_label.setObjectName(u"translucent_window_label")
        self.translucent_window_label.setGeometry(QRect(20, 20, 354, 820))
        self.translucent_window_label.setStyleSheet(u"background-color: qlinegradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius:20px;\n"
"")
        self.translucent_window_label_2 = QLabel(self.widget)
        self.translucent_window_label_2.setObjectName(u"translucent_window_label_2")
        self.translucent_window_label_2.setGeometry(QRect(50, 70, 291, 721))
        self.translucent_window_label_2.setStyleSheet(u"background: rgba(0,0,0,100);\n"
"border-radius : 15px;")
        self.pushButton = QPushButton(self.widget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(60, 80, 41, 41))
        self.Location_Label = QLabel(self.widget)
        self.Location_Label.setObjectName(u"Location_Label")
        self.Location_Label.setGeometry(QRect(60, 150, 151, 16))
        font = QFont()
        font.setFamily(u"Corbel")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Location_Label.setFont(font)
        self.Location_Label.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.Location_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.Location_Label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        self.Loc_Name_Label = QLabel(self.widget)
        self.Loc_Name_Label.setObjectName(u"Loc_Name_Label")
        self.Loc_Name_Label.setGeometry(QRect(80, 180, 251, 41))
        font1 = QFont()
        font1.setFamily(u"Corbel")
        font1.setPointSize(27)
        self.Loc_Name_Label.setFont(font1)
        self.Loc_Name_Label.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.Loc_Name_Label.setAlignment(Qt.AlignCenter)
        self.Loc_Name_Label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Out_weath_Label = QLabel(self.widget)
        self.Out_weath_Label.setObjectName(u"Out_weath_Label")
        self.Out_weath_Label.setGeometry(QRect(80, 230, 241, 31))
        font2 = QFont()
        font2.setFamily(u"Corbel")
        font2.setPointSize(15)
        self.Out_weath_Label.setFont(font2)
        self.Out_weath_Label.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.Out_weath_Label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Weather_Today_Label = QLabel(self.widget)
        self.Weather_Today_Label.setObjectName(u"Weather_Today_Label")
        self.Weather_Today_Label.setGeometry(QRect(60, 320, 161, 26))
        self.Weather_Today_Label.setFont(font)
        self.Weather_Today_Label.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        self.Weather_Today_Label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        #self.Weather_Today_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.temp_label = QLabel(self.widget)
        self.temp_label.setObjectName(u"temp_label")
        self.temp_label.setGeometry(QRect(80, 370, 121, 30))
        self.temp_label.setFont(font2)
        self.temp_label.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.temp_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.temp_label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        self.precipi_label = QLabel(self.widget)
        self.precipi_label.setObjectName(u"precipi_label")
        self.precipi_label.setGeometry(QRect(80, 420, 121, 30))
        self.precipi_label.setFont(font2)
        self.precipi_label.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.precipi_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.precipi_label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        self.hum_label = QLabel(self.widget)
        self.hum_label.setObjectName(u"hum_label")
        self.hum_label.setGeometry(QRect(80, 470, 121, 30))
        self.hum_label.setFont(font2)
        self.hum_label.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.hum_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.hum_label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        self.windspeed_label = QLabel(self.widget)
        self.windspeed_label.setObjectName(u"windspeed_label")
        self.windspeed_label.setGeometry(QRect(80, 530, 121, 30))
        self.windspeed_label.setFont(font2)
        self.windspeed_label.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.windspeed_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.windspeed_label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
        self.disp_humidity = QLabel(self.widget)
        self.disp_humidity.setObjectName(u"disp_humidity")
        self.disp_humidity.setGeometry(QRect(210, 370, 121, 30))
        self.disp_humidity.setFont(font2)
        self.disp_humidity.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.disp_humidity.setAlignment(Qt.AlignCenter)
        self.disp_humidity.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.disp_precipitation = QLabel(self.widget)
        self.disp_precipitation.setObjectName(u"disp_precipitation")
        self.disp_precipitation.setGeometry(QRect(210, 420, 121, 30))
        self.disp_precipitation.setFont(font2)
        self.disp_precipitation.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.disp_precipitation.setAlignment(Qt.AlignCenter)
        self.disp_precipitation.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.disp_wind_speed = QLabel(self.widget)
        self.disp_wind_speed.setObjectName(u"disp_wind_speed")
        self.disp_wind_speed.setGeometry(QRect(210, 470, 121, 30))
        self.disp_wind_speed.setFont(font2)
        self.disp_wind_speed.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.disp_wind_speed.setAlignment(Qt.AlignCenter)
        self.disp_wind_speed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.disp_temp = QLabel(self.widget)
        self.disp_temp.setObjectName(u"disp_temp")
        self.disp_temp.setGeometry(QRect(210, 530, 121, 30))
        self.disp_temp.setFont(font2)
        self.disp_temp.setStyleSheet(u"color:rgba(255, 255, 255, 210);")
        #self.disp_temp.setAlignment(Qt.AlignCenter)
        self.disp_temp.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.picture_label.setText("")
        self.translucent_window_label.setText("")
        self.translucent_window_label_2.setText("")
        #self.pushButton.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.Location_Label.setText(QCoreApplication.translate("MainWindow", u"Your Location :", None))
        self.Loc_Name_Label.setText(QCoreApplication.translate("MainWindow", u"Bengaluru, India", None))
        self.Out_weath_Label.setText(QCoreApplication.translate("MainWindow", u"Sunny ", None))
        self.Weather_Today_Label.setText(QCoreApplication.translate("MainWindow", u"Weather Today :", None))
        self.temp_label.setText(QCoreApplication.translate("MainWindow", u"Temperature : ", None))
        self.precipi_label.setText(QCoreApplication.translate("MainWindow", u"Precipitation :", None))
        self.hum_label.setText(QCoreApplication.translate("MainWindow", u"Humidity : ", None))
        self.windspeed_label.setText(QCoreApplication.translate("MainWindow", u"Wind Speed : ", None))
        self.disp_humidity.setText(QCoreApplication.translate("MainWindow", u"29 C", None))
        self.disp_precipitation.setText(QCoreApplication.translate("MainWindow", u"29 C", None))
        self.disp_wind_speed.setText(QCoreApplication.translate("MainWindow", u"29 C", None))
        self.disp_temp.setText(QCoreApplication.translate("MainWindow", u"29 C", None))
        self.pushButton.clicked.connect(QCoreApplication.instance().quit)
        self.pushButton.setIcon(QIcon('21159.png'))
        self.pushButton.setIconSize(QSize(30,30))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

