# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginInterface.ui'
#
# Created by: PyQt6 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from curses import ERR
#from pickle import TRUE
#from tkinter import Button


from PyQt6 import QtCore, QtGui, QtWidgets, uic
from PyQt6.QtWidgets import *
from PyQt6.QtCore import *
from PyQt6.QtGui import *
import sys
import os
import subprocess
from os import *




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 900)
        MainWindow.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        MainWindow.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 20, 581, 929))
        self.widget.setStyleSheet(u"QPushButton#pushButton{\n"
"	background-color: qlinegradient(spread:pad, x1:0, y1:0,505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"	background-color: qlinegradient(spread:pad, x1:0, y1:0,505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"	padding-left:5px;\n"
"	padding:top;\n"
"	background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_6, #pushButton_7{\n"
"	background-color: rgba(0, 0, 0, 0);\n"
"	color:rgba(85, 98, 112, 255);\n"
"}\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_6:hover, #pushButton_7:hover{\n"
"	color: rgba(155, 168, 182, 200);\n"
"}\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_6:pressed, #pushButton_7:pressed{\n"
""
                        "	padding-left:5px;\n"
"	padding:top;\n"
"	background-color:rgba(115, 128, 142, 255);\n"
"}")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 40, 500, 780))
        self.label.setStyleSheet(u"border-image: url(7f631e577ed5e5ffbbce726f8ec03489.jpg);\n"
"border-radius:20px;\n"
"")
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 20, 530, 820))
        self.label_2.setStyleSheet(u"background-color: qlinegradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius:20px;\n"
"")
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 70, 440, 720))
        self.label_3.setStyleSheet(u"background: rgba(0,0,0,100);\n"
"border-radius : 15px")
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 110, 281, 44))
        font = QFont()
        font.setFamily(u"Corbel")
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        #self.label_4.setTextFormat(Qt.PlainText)
        self.label_4.setTextFormat(Qt.TextFormat.PlainText)

        self.label_4.setScaledContents(False)
        #self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButton_3 = QPushButton(self.widget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(470, 90, 31, 31))
        font1 = QFont()
        font1.setFamily(u"Corbel")
        font1.setPointSize(21)
        font1.setBold(True)
        font1.setWeight(75)
        self.pushButton_3.setFont(font1)
        """self.pushButton_3.setStyleSheet(u"QPushButton#pushButton_3{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(122, 63, 147, 255), stop:1 rgba(219, 147, 232, 255));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_3:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(122, 83, 167, 255), stop:1 rgba(239, 167, 252, 255));\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"	padding-left:5px;\n"
"	padding-top:5px;\n"
"	background-color:rgba(239, 167, 252, 200);\n"
"}\n"
"")"""
        self.pushButton_2 = QPushButton(self.widget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(210, 310, 161, 41))
        font2 = QFont()
        font2.setFamily(u"Corbel")
        font2.setPointSize(16)
        self.pushButton_2.setFont(font2)
        self.pushButton_2.setStyleSheet(u"QPushButton#pushButton_2{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 71, 120, 255), stop:1 rgba(0, 41, 69, 255));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 91, 140, 255), stop:1 rgba(0, 61, 89, 255));\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"	padding-left:5px;\n"
"	padding-top:5px;\n"
"	background-color:rgba(65, 75, 116, 200);\n"
"}\n"   
"")
        self.pushButton_4 = QPushButton(self.widget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(200, 380, 181, 41))
        self.pushButton_4.setFont(font2)
        self.pushButton_4.setStyleSheet(u"QPushButton#pushButton_4{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 71, 120, 255), stop:1 rgba(0, 41, 69, 255));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_4:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 91, 140, 255), stop:1 rgba(0, 61, 89, 255));\n"
"}\n"
"QPushButton#pushButton_4:pressed{\n"
"	padding-left:5px;\n"
"	padding-top:5px;\n"
"	background-color:rgba(65, 75, 116, 200);\n"
"}\n"   
"")
        self.pushButton_6 = QPushButton(self.widget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(200, 450, 181, 41))
        self.pushButton_6.setFont(font2)
        self.pushButton_6.setStyleSheet(u"QPushButton#pushButton_6{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 71, 120, 255), stop:1 rgba(0, 41, 69, 255));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_6:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 91, 140, 255), stop:1 rgba(0, 61, 89, 255));\n"
"}\n"
"QPushButton#pushButton_6:pressed{\n"
"	padding-left:5px;\n"
"	padding-top:5px;\n"
"	background-color:rgba(65, 75, 116, 200);\n"
"}\n"   
"")
        self.pushButton_7 = QPushButton(self.widget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(100, 550, 391, 41))
        self.pushButton_7.setFont(font2)
        self.pushButton_7.setStyleSheet(u"QPushButton#pushButton_7{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 71, 120, 255), stop:1 rgba(0, 41, 69, 255));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_7:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 91, 140, 255), stop:1 rgba(0, 61, 89, 255));\n"
"}\n"
"QPushButton#pushButton_7:pressed{\n"
"	padding-left:5px;\n"
"	padding-top:5px;\n"
"	background-color:rgba(65, 75, 116, 200);\n"
"}\n"   
"")
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(150, 200, 281, 44))
        font3 = QFont()
        font3.setFamily(u"Corbel")
        font3.setPointSize(22)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        #self.label_5.setTextFormat(Qt.PlainText)
        self.label_5.setTextFormat(Qt.TextFormat.PlainText)
        self.label_5.setScaledContents(False)
        #self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Water Quality Index", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Puttenahalli Lake", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Mahadevapura Lake", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Madivala Lake", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Calculate the WQI with parameters", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Choose A Lake", None))
        self.pushButton_3.clicked.connect(QCoreApplication.instance().quit)
        self.pushButton_7.clicked.connect(self.con_calc_wqi)
        
    def con_lake_1(self):
        p = subprocess.call("")
     
    def call_lake_2(self):
        p = subprocess.call("")
        
    def con_lake_3(self):
        p = subprocess.call("")
        
    def con_calc_wqi(self):
        p = subprocess.call("python3 WQI_Interface_2_New.py 1", shell = True)
        


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

