# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from curses import ERR
#from pickle import TRUE
#from tkinter import Button


from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import sys
import os
import subprocess
from os import *



var = ""

#wqi = str(wqi)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 900)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 20, 581, 929))
        self.water_quality_index = "as"
        self.widget.setStyleSheet(u"QPushButton#pushButton{\n"
"	background-color: qlinegradient(spread:pad, x1:0, y1:0,505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"	background-color: qlinegradient(spread:pad, x1:0, y1:0,505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"	padding-left:5px;\n"
"	padding:top;\n"
"	background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_6, #pushButton_7{\n"
"	background-color: rgba(0, 0, 0, 0);\n"
"	color:rgba(85, 98, 112, 255);\n"
"}\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_6:hover, #pushButton_7:hover{\n"
"	color: rgba(155, 168, 182, 200);\n"
"}\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_6:pressed, #pushButton_7:pressed{\n"
""
                        "	padding-left:5px;\n"
"	padding:top;\n"
"	background-color:rgba(115, 128, 142, 255);\n"
"}")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 40, 500, 780))
        self.label.setStyleSheet(u"border-image: url(7f631e577ed5e5ffbbce726f8ec03489.jpg);\n"
"border-radius:20px;\n"
"")
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 20, 530, 820))
        self.label_2.setStyleSheet(u"background-color: qlinegradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius:20px;\n"
"")
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 70, 440, 720))
        self.label_3.setStyleSheet(u"background: rgba(0,0,0,100);\n"
"border-radius : 15px")
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 110, 281, 44))
        font = QFont()
        font.setFamily(u"Corbel")
        font.setPointSize(22)
        #font.setBold(True)
        font.setUnderline(False)
        #font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        self.label_4.setTextFormat(Qt.PlainText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.pushButton_3 = QPushButton(self.widget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(470, 90, 31, 31))
        font1 = QFont()
        font1.setFamily(u"Corbel")
        font1.setPointSize(21)
        font1.setBold(True)
        font1.setWeight(75)
        self.pushButton_3.setFont(font1)
        self.pushButton_3.setStyleSheet(u"color:rgba(255,255,255,210);")
        self.pushButton_7 = QPushButton(self.widget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(190, 560, 221, 31))
        font2 = QFont()
        font2.setFamily(u"Corbel")
        font2.setPointSize(16)
        self.pushButton_7.setFont(font2)
        self.pushButton_7.setStyleSheet(u"QPushButton#pushButton_7{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 71, 120, 255), stop:1 rgba(0, 41, 69, 255));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_7:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0.364, y1:1, x2:1, y2:1, stop:0 rgba(0, 91, 140, 255), stop:1 rgba(0, 61, 89, 255));\n"
"}\n"
"QPushButton#pushButton_7:pressed{\n"
"	padding-left:5px;\n"
"	padding-top:5px;\n"
"	background-color:rgba(65, 75, 116, 200);\n"
"}\n"
"")
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(90, 240, 141, 44))
        font3 = QFont()
        font3.setFamily(u"Corbel")
        font3.setPointSize(16)
        font3.setBold(False)
        font3.setWeight(50)
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        self.label_5.setTextFormat(Qt.PlainText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(90, 290, 171, 44))
        self.label_6.setFont(font3)
        self.label_6.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        self.label_6.setTextFormat(Qt.PlainText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(90, 340, 101, 44))
        self.label_7.setFont(font3)
        self.label_7.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        self.label_7.setTextFormat(Qt.PlainText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 390, 141, 44))
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        self.label_8.setTextFormat(Qt.PlainText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(90, 440, 141, 44))
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        self.label_9.setTextFormat(Qt.PlainText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.lineEdit = QLineEdit(self.widget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(270, 250, 211, 20))
        self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lineEdit_2 = QLineEdit(self.widget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(270, 302, 211, 20))
        self.lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lineEdit_3 = QLineEdit(self.widget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(270, 350, 211, 20))
        self.lineEdit_3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lineEdit_4 = QLineEdit(self.widget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(270, 400, 211, 20))
        self.lineEdit_4.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lineEdit_5 = QLineEdit(self.widget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(270, 450, 211, 20))
        self.lineEdit_5.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(90, 620, 141, 44))
        self.label_10.setFont(font3)
        self.label_10.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        self.label_10.setTextFormat(Qt.PlainText)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(290, 625, 171, 28))
        self.label_11.setFont(font3)
        self.label_11.setStyleSheet(u"color:rgba(255, 255, 255, 210);\n"
"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)


    def getph(self):
        global phlevel
        global temperature
        global bod
        global turbidity
        global ammonia
        #global water_quality_index
        
        phlevel = self.lineEdit.text()
        temperature = self.lineEdit.text()
        bod = self.lineEdit_3.text()
        turbidity = self.lineEdit_4.text()
        ammonia = self.lineEdit_5.text()
        
        phlevel= int(phlevel)
        temperature = int(temperature)
        bod = int(bod)
        turbidity = int(turbidity)
        ammonia = int(ammonia)
        
        water_ph = (phlevel/8.5)*100
        water_temp = (temperature/25)*100
        water_bod = (bod/10)*100
        water_turbidity = (turbidity/5)*100
        water_ammonia = (ammonia/1.2)*100
        
        self.water_quality_index = ((water_ph*0.0910) + (water_temp*0.0309) + (water_turbidity*0.1549) + (water_bod*0.0774) + (water_ammonia*0.6455))
        self.water_quality_index = str(self.water_quality_index)
        #print("Hello")
        self.label_11.setText(QCoreApplication.translate("MainWindow", self.water_quality_index, None))
        

    
        

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Water Quality Index", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Calculate the WQI ", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Enter pH Level:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Enter Temperature:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Enter BOD:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Enter Turbidity: ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Enter Ammonia:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Calculated WQI:", None))
        self.pushButton_7.clicked.connect(self.getph)
        self.pushButton_3.clicked.connect(QCoreApplication.instance().quit)
        #self.label_11.setText(QCoreApplication.translate("MainWindow", u"", None))
        

        
        

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

